Application Connectted to the Database
Eng-NUREDDIN/Cook2Door pull request #23
Opened 2023-07-08 20:28 UTC by Eng-NUREDDIN

2023-07-08 21:01 UTC, radmanlo commented on src/models/cookSchema.js
> +  },
I think it is a good idea we have created_at attribute here in order to find out when it is created (Most probably I forgot to put in the design).

2023-07-08 21:01 UTC, radmanlo commented on src/models/cookSchema.js
> +    type: String,
it better that cook_name be required also

2023-07-08 21:02 UTC, radmanlo commented on src/models/cookSchema.js
> +  },
I think it is a good idea we have created_at attribute here in order to find out when it is created (Most probably I forgot to put in the design).

2023-07-08 21:03 UTC, radmanlo commented on src/models/cookSchema.js
> +module.exports = mongoose.model('Cook', cookSchema);
Since we have cook as router it is good idea that  Coolk be CookSchema

2023-07-09 13:48 UTC, radmanlo requested changes
Please change the code based on the comments I write. Thank you

2023-07-10 10:12 UTC, radmanlo approved these changes

2023-07-10 10:14 UTC, afrakucukaydin approved these changes

2023-07-10 10:51 UTC, talal-bakkour approved these changes

2023-07-10 11:04 UTC, merged