adding cook controler api
Eng-NUREDDIN/Cook2Door pull request #36
Opened 2023-07-12 10:24 UTC by Eng-NUREDDIN

2023-07-12 13:42 UTC, radmanlo approved these changes
it is good work thank, you if you try it and it works, we can merge.

2023-07-12 18:34 UTC, radmanlo requested changes

2023-07-12 18:34 UTC, radmanlo commented on src/models/cookSchema.js
>    created_at: {
could you please add a password attribute here also?

2023-07-13 12:16 UTC, talal-bakkour approved these changes

2023-07-13 12:16 UTC, radmanlo approved these changes

2023-07-13 12:21 UTC, afrakucukaydin approved these changes

2023-07-13 12:30 UTC, merged