#41 implementing swager for cook
Eng-NUREDDIN/Cook2Door pull request #49
Opened 2023-07-13 17:04 UTC by Eng-NUREDDIN

2023-07-13 17:15 UTC, radmanlo requested changes

2023-07-13 17:15 UTC, radmanlo commented on src/routes/cook.js
> + *             $ref: '#/components/schemas/Cook'
you should add cook in the schema of the swagger.js file. Look at the file there is schema and in there there is dish_add and dish_update, you should have those for cook add and cook update. please solve this.

2023-07-13 17:15 UTC, radmanlo commented on src/routes/cook.js
> + *             $ref: '#/components/schemas/Cook'
here is also cook_update if you look at my code in configuration/swagger.js you will find out

2023-07-13 21:49 UTC, radmanlo requested changes

2023-07-13 21:49 UTC, radmanlo commented on src/configuration/swagger.js
> +        Dish_Update: {
This should be cook_update I think

2023-07-14 08:57 UTC, radmanlo approved these changes

2023-07-14 09:53 UTC, afrakucukaydin approved these changes

2023-07-15 20:18 UTC, merged