Customer swagger implemented #40
Eng-NUREDDIN/Cook2Door pull request #54
Opened 2023-07-14 11:20 UTC by afrakucukaydin

2023-07-14 11:38 UTC, radmanlo requested changes

2023-07-14 11:38 UTC, radmanlo commented on src/routes/customer.js
> + *             $ref: '#/components/schemas/Customer'
You should create a schema for the customer in the configuration/swagger.js. look at the swagger.js you will find out

2023-07-14 11:38 UTC, radmanlo commented on src/routes/customer.js
> + *             $ref: '#/components/schemas/Customer'
Also for updates you need to create a Schema in swagger.js

2023-07-16 11:12 UTC, Eng-NUREDDIN commented on src/configuration/swagger.js
> +        },
please pull the updates from the main branch first there are many schemas missing

2023-07-17 10:59 UTC, radmanlo requested changes

2023-07-17 10:59 UTC, radmanlo commented on src/configuration/swagger.js
> +            created_at: {
Created_at has a default value which is now so you do not need to ask for that from the user.

2023-07-17 10:59 UTC, radmanlo commented on src/configuration/swagger.js
> +            provider: {
for now, we do not need provider and provider_id please remove these 2

2023-07-17 10:59 UTC, radmanlo commented on src/configuration/swagger.js
> +            provider_id: {
for now, we do not need provider and provider_id please remove these 2

2023-07-17 12:58 UTC, radmanlo approved these changes

2023-07-18 08:41 UTC, Eng-NUREDDIN approved these changes

2023-07-18 10:02 UTC, talal-bakkour approved these changes

2023-07-19 05:49 UTC, merged