Talal bakkour/issue42
Eng-NUREDDIN/Cook2Door pull request #57
Opened 2023-07-15 21:41 UTC by talal-bakkour

2023-07-16 09:29 UTC, Eng-NUREDDIN commented on src/routes/dish.js
> + *         description: Dishe successfully deleted
it must be order successfully deleted not Dish

2023-07-16 09:30 UTC, Eng-NUREDDIN commented on src/routes/dish.js
> + *         description: Dishe not found
same here Order not Dish

2023-07-16 09:32 UTC, Eng-NUREDDIN commented on src/routes/order.js
> + *     summary: Delete a dish by ID
same here Order not Dish

2023-07-17 10:44 UTC, radmanlo requested changes

2023-07-17 10:44 UTC, radmanlo commented on src/routes/order.js
> + *             $ref: '#/components/schemas/Order_Add'
Order_Add should be Schema in swagger.js file. I cannot see this schema in theswagger file.

2023-07-17 10:44 UTC, radmanlo commented on src/routes/order.js
> + *             $ref: '#/components/schemas/Order_Update'
Order_Update also be in swagger.js in schema part

2023-07-17 13:01 UTC, radmanlo approved these changes

2023-07-18 06:14 UTC, afrakucukaydin approved these changes

2023-07-18 06:26 UTC, merged